import { NextResponse } from "next/server";
import { z } from "zod";
import { verify } from "@/lib/tokens";
import { supabaseAdmin, isServerConfigured } from "@/lib/supabase/server";
import { nanoid } from "nanoid";

// POST /api/photos/upload-url
// body: { token, contentType, takenAt? }
// returns: { uploadUrl, photoId, key }
//
// MVP: signed URL is generated by Supabase Storage if R2 is not configured.
// In production, swap for an R2 presigned PUT (AWS S3 signature v4).

const Body = z.object({
  token: z.string().min(8),
  contentType: z.string().regex(/^image\//),
  takenAt: z.string().datetime().optional(),
  caption: z.string().max(280).optional(),
});

export async function POST(req: Request) {
  if (!isServerConfigured()) {
    return NextResponse.json({ error: "Supabase not configured" }, { status: 503 });
  }
  const json = await req.json().catch(() => null);
  const parsed = Body.safeParse(json);
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });
  }
  const claims = verify(parsed.data.token);
  if (!claims) return NextResponse.json({ error: "invalid_token" }, { status: 401 });

  const supabase = supabaseAdmin();

  // Verify the raw part of the token matches the yearbook's invite_token
  const { data: yb, error: ybErr } = await supabase
    .from("yearbooks")
    .select("id, invite_token, admin_token")
    .eq("id", claims.yearbookId)
    .single();
  if (ybErr || !yb) return NextResponse.json({ error: "yearbook_not_found" }, { status: 404 });
  const expected = claims.role === "admin" ? yb.admin_token : yb.invite_token;
  if (expected !== claims.raw) return NextResponse.json({ error: "stale_token" }, { status: 401 });

  // Insert a pending photo row + return a Supabase Storage signed upload URL.
  const photoId = crypto.randomUUID();
  const ext = parsed.data.contentType.split("/")[1] ?? "jpg";
  const key = `${claims.yearbookId}/${photoId}.${ext}`;

  const { data: signed, error: signErr } = await supabase.storage
    .from("photos")
    .createSignedUploadUrl(key);
  if (signErr || !signed) {
    return NextResponse.json({ error: signErr?.message ?? "sign_failed" }, { status: 500 });
  }

  await supabase.from("photos").insert({
    id: photoId,
    yearbook_id: claims.yearbookId,
    r2_key: key,
    taken_at: parsed.data.takenAt ?? new Date().toISOString(),
    caption: parsed.data.caption,
    status: "pending", // post-processing worker promotes to 'published'
  });

  return NextResponse.json({
    uploadUrl: signed.signedUrl,
    token: signed.token,
    photoId,
    key,
  });
}
