-- Yearbook 2026 — initial schema
-- Run with: supabase db push  (or psql -f this file)

create extension if not exists "pgcrypto";

-- One yearbook = one event with a shareable invite token
create table yearbooks (
  id            uuid primary key default gen_random_uuid(),
  slug          text unique not null,
  title         text not null,
  cover_emoji   text default '📒',
  invite_token  text not null,    -- shared in the URL: /y/<slug>?k=<token>
  admin_token   text not null,    -- only the creator gets this
  theme         jsonb default '{}'::jsonb,
  created_at    timestamptz default now()
);

-- Anonymous contributors: identified by a cookie-stored UUID, NO password
create table contributors (
  id            uuid primary key default gen_random_uuid(),
  yearbook_id   uuid not null references yearbooks(id) on delete cascade,
  display_name  text not null,
  emoji         text default '🙂',
  fingerprint   text,            -- soft anti-abuse signal
  created_at    timestamptz default now()
);
create index on contributors(yearbook_id);

-- People = face clusters, renamable by any contributor
create table people (
  id              uuid primary key default gen_random_uuid(),
  yearbook_id     uuid not null references yearbooks(id) on delete cascade,
  name            text not null,
  cover_photo_id  uuid,
  embedding       vector(128),    -- needs pgvector ext; optional
  created_at      timestamptz default now()
);
create index on people(yearbook_id);

create table photos (
  id            uuid primary key default gen_random_uuid(),
  yearbook_id   uuid not null references yearbooks(id) on delete cascade,
  uploader_id   uuid references contributors(id) on delete set null,
  r2_key        text not null,                     -- object key in R2
  thumb_key     text,
  width         int, height int,
  taken_at      timestamptz not null,              -- EXIF DateTimeOriginal, fallback to upload time
  uploaded_at   timestamptz default now(),
  exif          jsonb default '{}'::jsonb,
  phash         text,                              -- perceptual hash for de-dup
  nsfw_score    real default 0,
  caption       text,
  status        text not null default 'published'  -- published | pending | hidden
                check (status in ('published','pending','hidden'))
);
create index on photos(yearbook_id, taken_at);
create index on photos(yearbook_id, status);

-- Many-to-many: a photo features 0..n people
create table photo_people (
  photo_id   uuid not null references photos(id) on delete cascade,
  person_id  uuid not null references people(id) on delete cascade,
  bbox       jsonb,
  confidence real,
  primary key (photo_id, person_id)
);

-- Sections = chapters in the timeline (auto-generated by month, or named manually)
create table sections (
  id            uuid primary key default gen_random_uuid(),
  yearbook_id   uuid not null references yearbooks(id) on delete cascade,
  title         text not null,
  start_date    timestamptz not null,
  end_date      timestamptz not null,
  position      int not null default 0,
  created_at    timestamptz default now()
);
create index on sections(yearbook_id, position);

-- Customizable layout: each block has a 12-col grid position inside its section
create table layout_blocks (
  id          uuid primary key default gen_random_uuid(),
  section_id  uuid not null references sections(id) on delete cascade,
  type        text not null check (type in ('photo','text','title','polaroid')),
  photo_id    uuid references photos(id) on delete cascade,
  body        text,
  x int not null, y int not null, w int not null, h int not null,
  rotate      real default 0,
  props       jsonb default '{}'::jsonb,
  updated_at  timestamptz default now()
);
create index on layout_blocks(section_id);

-- Lightweight comments under a photo
create table comments (
  id              uuid primary key default gen_random_uuid(),
  photo_id        uuid not null references photos(id) on delete cascade,
  contributor_id  uuid references contributors(id) on delete set null,
  body            text not null,
  created_at      timestamptz default now()
);
create index on comments(photo_id, created_at);

-- ---------- RLS ---------- (Supabase)
alter table yearbooks      enable row level security;
alter table contributors   enable row level security;
alter table people         enable row level security;
alter table photos         enable row level security;
alter table photo_people   enable row level security;
alter table sections       enable row level security;
alter table layout_blocks  enable row level security;
alter table comments       enable row level security;

-- The Edge Function that signs the invite/admin token sets a JWT claim
-- "yb" = yearbook_id and "role" = 'contributor' | 'admin'.
-- These policies assume that claim is present.

create policy "read own yearbook"
  on yearbooks for select
  using (id::text = current_setting('request.jwt.claims', true)::jsonb->>'yb');

create policy "contribute to own yearbook"
  on photos for insert
  with check (yearbook_id::text = current_setting('request.jwt.claims', true)::jsonb->>'yb');

create policy "read own yearbook photos"
  on photos for select
  using (yearbook_id::text = current_setting('request.jwt.claims', true)::jsonb->>'yb');

-- (Repeat similar policies for the other tables — kept short here.)
